/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.szlabsun.wqimc.api.manager;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-07-05")
public class ConsumableConfigItem implements org.apache.thrift.TBase<ConsumableConfigItem, ConsumableConfigItem._Fields>, java.io.Serializable, Cloneable, Comparable<ConsumableConfigItem> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ConsumableConfigItem");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("text", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CYCLE_FIELD_DESC = new org.apache.thrift.protocol.TField("cycle", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField LAST_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("lastTime", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ConsumableConfigItemStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ConsumableConfigItemTupleSchemeFactory();

  public java.lang.String name; // required
  public java.lang.String text; // required
  public double cycle; // required
  public long lastTime; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    TEXT((short)2, "text"),
    CYCLE((short)3, "cycle"),
    LAST_TIME((short)4, "lastTime");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // TEXT
          return TEXT;
        case 3: // CYCLE
          return CYCLE;
        case 4: // LAST_TIME
          return LAST_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CYCLE_ISSET_ID = 0;
  private static final int __LASTTIME_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TEXT, new org.apache.thrift.meta_data.FieldMetaData("text", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CYCLE, new org.apache.thrift.meta_data.FieldMetaData("cycle", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.LAST_TIME, new org.apache.thrift.meta_data.FieldMetaData("lastTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ConsumableConfigItem.class, metaDataMap);
  }

  public ConsumableConfigItem() {
  }

  public ConsumableConfigItem(
    java.lang.String name,
    java.lang.String text,
    double cycle,
    long lastTime)
  {
    this();
    this.name = name;
    this.text = text;
    this.cycle = cycle;
    setCycleIsSet(true);
    this.lastTime = lastTime;
    setLastTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ConsumableConfigItem(ConsumableConfigItem other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetText()) {
      this.text = other.text;
    }
    this.cycle = other.cycle;
    this.lastTime = other.lastTime;
  }

  public ConsumableConfigItem deepCopy() {
    return new ConsumableConfigItem(this);
  }

  @Override
  public void clear() {
    this.name = null;
    this.text = null;
    setCycleIsSet(false);
    this.cycle = 0.0;
    setLastTimeIsSet(false);
    this.lastTime = 0;
  }

  public java.lang.String getName() {
    return this.name;
  }

  public ConsumableConfigItem setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public java.lang.String getText() {
    return this.text;
  }

  public ConsumableConfigItem setText(java.lang.String text) {
    this.text = text;
    return this;
  }

  public void unsetText() {
    this.text = null;
  }

  /** Returns true if field text is set (has been assigned a value) and false otherwise */
  public boolean isSetText() {
    return this.text != null;
  }

  public void setTextIsSet(boolean value) {
    if (!value) {
      this.text = null;
    }
  }

  public double getCycle() {
    return this.cycle;
  }

  public ConsumableConfigItem setCycle(double cycle) {
    this.cycle = cycle;
    setCycleIsSet(true);
    return this;
  }

  public void unsetCycle() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CYCLE_ISSET_ID);
  }

  /** Returns true if field cycle is set (has been assigned a value) and false otherwise */
  public boolean isSetCycle() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CYCLE_ISSET_ID);
  }

  public void setCycleIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CYCLE_ISSET_ID, value);
  }

  public long getLastTime() {
    return this.lastTime;
  }

  public ConsumableConfigItem setLastTime(long lastTime) {
    this.lastTime = lastTime;
    setLastTimeIsSet(true);
    return this;
  }

  public void unsetLastTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LASTTIME_ISSET_ID);
  }

  /** Returns true if field lastTime is set (has been assigned a value) and false otherwise */
  public boolean isSetLastTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LASTTIME_ISSET_ID);
  }

  public void setLastTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LASTTIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case TEXT:
      if (value == null) {
        unsetText();
      } else {
        setText((java.lang.String)value);
      }
      break;

    case CYCLE:
      if (value == null) {
        unsetCycle();
      } else {
        setCycle((java.lang.Double)value);
      }
      break;

    case LAST_TIME:
      if (value == null) {
        unsetLastTime();
      } else {
        setLastTime((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case TEXT:
      return getText();

    case CYCLE:
      return getCycle();

    case LAST_TIME:
      return getLastTime();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case TEXT:
      return isSetText();
    case CYCLE:
      return isSetCycle();
    case LAST_TIME:
      return isSetLastTime();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ConsumableConfigItem)
      return this.equals((ConsumableConfigItem)that);
    return false;
  }

  public boolean equals(ConsumableConfigItem that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_text = true && this.isSetText();
    boolean that_present_text = true && that.isSetText();
    if (this_present_text || that_present_text) {
      if (!(this_present_text && that_present_text))
        return false;
      if (!this.text.equals(that.text))
        return false;
    }

    boolean this_present_cycle = true;
    boolean that_present_cycle = true;
    if (this_present_cycle || that_present_cycle) {
      if (!(this_present_cycle && that_present_cycle))
        return false;
      if (this.cycle != that.cycle)
        return false;
    }

    boolean this_present_lastTime = true;
    boolean that_present_lastTime = true;
    if (this_present_lastTime || that_present_lastTime) {
      if (!(this_present_lastTime && that_present_lastTime))
        return false;
      if (this.lastTime != that.lastTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetText()) ? 131071 : 524287);
    if (isSetText())
      hashCode = hashCode * 8191 + text.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(cycle);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lastTime);

    return hashCode;
  }

  @Override
  public int compareTo(ConsumableConfigItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetText()).compareTo(other.isSetText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.text, other.text);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCycle()).compareTo(other.isSetCycle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCycle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cycle, other.cycle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLastTime()).compareTo(other.isSetLastTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastTime, other.lastTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ConsumableConfigItem(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("text:");
    if (this.text == null) {
      sb.append("null");
    } else {
      sb.append(this.text);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cycle:");
    sb.append(this.cycle);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastTime:");
    sb.append(this.lastTime);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ConsumableConfigItemStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ConsumableConfigItemStandardScheme getScheme() {
      return new ConsumableConfigItemStandardScheme();
    }
  }

  private static class ConsumableConfigItemStandardScheme extends org.apache.thrift.scheme.StandardScheme<ConsumableConfigItem> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ConsumableConfigItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.text = iprot.readString();
              struct.setTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CYCLE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.cycle = iprot.readDouble();
              struct.setCycleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LAST_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastTime = iprot.readI64();
              struct.setLastTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ConsumableConfigItem struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.text != null) {
        oprot.writeFieldBegin(TEXT_FIELD_DESC);
        oprot.writeString(struct.text);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CYCLE_FIELD_DESC);
      oprot.writeDouble(struct.cycle);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_TIME_FIELD_DESC);
      oprot.writeI64(struct.lastTime);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ConsumableConfigItemTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ConsumableConfigItemTupleScheme getScheme() {
      return new ConsumableConfigItemTupleScheme();
    }
  }

  private static class ConsumableConfigItemTupleScheme extends org.apache.thrift.scheme.TupleScheme<ConsumableConfigItem> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ConsumableConfigItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetName()) {
        optionals.set(0);
      }
      if (struct.isSetText()) {
        optionals.set(1);
      }
      if (struct.isSetCycle()) {
        optionals.set(2);
      }
      if (struct.isSetLastTime()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetText()) {
        oprot.writeString(struct.text);
      }
      if (struct.isSetCycle()) {
        oprot.writeDouble(struct.cycle);
      }
      if (struct.isSetLastTime()) {
        oprot.writeI64(struct.lastTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ConsumableConfigItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.text = iprot.readString();
        struct.setTextIsSet(true);
      }
      if (incoming.get(2)) {
        struct.cycle = iprot.readDouble();
        struct.setCycleIsSet(true);
      }
      if (incoming.get(3)) {
        struct.lastTime = iprot.readI64();
        struct.setLastTimeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

