/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.szlabsun.wqimc.api.manager;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RoleType implements org.apache.thrift.TEnum {
  Guest(0),
  Administrator(1),
  Engineer(2);

  private final int value;

  private RoleType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RoleType findByValue(int value) { 
    switch (value) {
      case 0:
        return Guest;
      case 1:
        return Administrator;
      case 2:
        return Engineer;
      default:
        return null;
    }
  }
}
